<style>
    body{
        background-color: gold;
    }
    .newsspec_13489--ap-iframe{
        width: 100%;
        height: 730px;
        border: 0;
        overflow: hidden;
    }
</style>

<iframe src="http://interactives.ap.org/2016/delegates-overview/?image=false&STATE=IA&date=0201&SITEID=BBC" scrolling="no" class="newsspec_13489--ap-iframe">
    Your browser does not support the <code>iframe</code> HTML tag. Try viewing this in a modern browser like Chrome, Safari, Firefox or Internet Explorer 9 or later.
</iframe>
