<!--NEWSSPEC-13489 -->
<style>
    body{
        margin: 0;
    }
    .newsspec_13489--ap-iframe{
        width: 100%;
        height: 730px;
        border: 0;
        overflow: hidden;
    }
</style>

<iframe src="http://interactives.ap.org/2016/primary-election-results/?STATE={{state}}&DATE={{date}}&SITEID=BBCTVELN&PARTY={{party}}&iframeid=GOP" scrolling="no" id="newsspec_13489--ap-iframe__GOP" class="newsspec_13489--ap-iframe">
    Your browser does not support the <code>iframe</code> HTML tag. Try viewing this in a modern browser like Chrome, Safari, Firefox or Internet Explorer 9 or later.
</iframe>

<script src="http://static.local.bbc.co.uk:1033/news/special/2016/newsspec_13489/content/js/postmessageresizer.js"></script>
<!--NEWSSPEC-13489-END -->
