<!--NEWSSPEC-13489 -->
<style>
    .newsspec_13489--ap-iframe{
        width: 100%;
        height: 730px;
        border: 0;
        overflow: hidden;
    }
</style>

<iframe src="http://interactives.ap.org/2016/delegates-overview/?image=false&STATE=IA&date=0201&SITEID=BBC" scrolling="no" id="newsspec_13489--ap-iframe" class="newsspec_13489--ap-iframe">
    Your browser does not support the <code>iframe</code> HTML tag. Try viewing this in a modern browser like Chrome, Safari, Firefox or Internet Explorer 9 or later.
</iframe>

<script src="http://static.local.bbc.co.uk:1033/news/special/2016/newsspec_13489/content/js/elementresizer.js"></script>
<script>
    var newsspec_13489_elementQueries = [
        {
            'min-width': 0,
            'height': 738
        },
        {
            'min-width': 245,
            'height': 568
        },
        {
            'min-width': 483,
            'height': 685
        },
        {
            'min-width': 641,
            'height': 358
        }
    ];
    ElementResizer({
        el: document.getElementById('newsspec_13489--ap-iframe'),
        elementQueries: newsspec_13489_elementQueries
    })
</script>
<!--NEWSSPEC-13489-END -->
